# Description:
#   This pipeline installs the K8S managers in the operations namespace
# Parameters:
#   Ignore Errors  true|false     When true, force the installation to continue even if errors occur

name: 0. Install K8S Managers

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Ignore Errors"
        required: false
        default: false
        type: boolean

jobs:
  do_install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Execute Force
        if: inputs.force == true
        run: |
          kubectl create ns operations || true
          helm repo add k8smanagers https://k8smanagers.blob.core.windows.net/helm/ || true
          helm install nodepoolmanager k8smanagers/nodepoolmanager -n operations || true
          helm install workloadmanager k8smanagers/workloadmanager -n operations || true

      - name: Execute
        if: inputs.force == false
        run: |
          kubectl create ns operations
          helm repo add k8smanagers https://k8smanagers.blob.core.windows.net/helm/
          helm install nodepoolmanager k8smanagers/nodepoolmanager -n operations
          helm install workloadmanager k8smanagers/workloadmanager -n operations
