name: Upgrade System Pool

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Execute or Cleanup"
        required: true
        default: "execute"
        type: choice
        options:
          - execute
          - cleanup
      version:
        description: "Target Kubernetes version"
        required: true

jobs:
  do_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Execute
        if: ${{ inputs.task == 'execute' }}
        run: |
          kubectl get pods -o wide -n jazz-x

      - name: Cleanup
        if: ${{ inputs.task == 'cleanup' }}
        run: |
          kubectl get services -o wide -n jazz-x
