name: Upgrade System Pool

on:
  workflow_dispatch: # ✅ Correct usage at workflow level

jobs:
  do_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          ls -l $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Test Kubectl
        run: |
          kubectl get pods -o wide -n jazz-x

  verification:
    needs: do_upgrade
    runs-on: ubuntu-latest
    steps:
      - name: User Confirmation Required
        run: echo "User triggered this manually!"
