# Description
#   This pipeline will upgrade only the system nodepool. In this example, the pool has been named "agentpool"
# Parameters:
#   Target Kubernetes Version    x.x.x    The version of Kubernetes to upgrade this node pool to
name: 1. Upgrade Agentpool Pool

concurrency:
  group: upgrade-agentpool-group

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target Kubernetes version"
        required: false

jobs:
  do_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Execute
        run: |
          SUB_ID=${{ vars.SUB_ID }}
          RESOURCE_GROUP=${{ vars.RESOURCE_GROUP }}
          CLUSTER_NAME=${{ vars.CLUSTER_NAME }}
          K8S_VERSION=${{ inputs.version }}
          
          cat <<EOF | kubectl apply -n operations -f -
          apiVersion: k8smanagers.greyridge.com/v1
          kind: NodePoolManager
          metadata:
            labels:
              app.kubernetes.io/name: nodepoolmanager
              app.kubernetes.io/managed-by: kustomize
            name: agentpool-upgrade
          spec:
            subscriptionId: $SUB_ID
            resourceGroup: $RESOURCE_GROUP
            clusterName: $CLUSTER_NAME
            nodePools:
              - name: agentpool
                properties: {
                  orchestratorVersion: $K8S_VERSION,
                }
          EOF

      - name: Wait
        run: |
          NODEPOOL_NAME=agentpool
          K8S_VERSION=${{ inputs.version }}
          
          while kubectl get nodes -o json | jq -r '.items[] | select(.metadata.labels["agentpool"]=="'"$NODEPOOL_NAME"'") | .status.nodeInfo.kubeletVersion' | grep -v "$K8S_VERSION"; do
            echo "🔄 Waiting for node pool '$NODEPOOL_NAME' to be at version '$K8S_VERSION'..."
            sleep 30
          done

      - name: Cleanup
        run: |
          kubectl -n operations delete nodepoolmanager.k8smanagers.greyridge.com/agentpool-upgrade

