name: Upgrade Agentpool Pool

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Execute or Cleanup"
        required: true
        default: "execute"
        type: choice
        options:
          - execute
          - cleanup
      version:
        description: "Target Kubernetes version (mandatory for execute)"
        required: false

jobs:
  do_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Execute
        if: ${{ inputs.task == 'execute' }}
        run: |
          SUB_ID=${{ vars.SUB_ID }}
          RESOURCE_GROUP=${{ vars.RESOURCE_GROUP }}
          CLUSTER_NAME=${{ vars.CLUSTER_NAME }}
          K8S_VERSION=${{ inputs.version }}
          
          cat <<EOF | kubectl apply -n operations -f -
          apiVersion: k8smanagers.greyridge.com/v1
          kind: NodePoolManager
          metadata:
            labels:
              app.kubernetes.io/name: nodepoolmanager
              app.kubernetes.io/managed-by: kustomize
            name: agentpool-upgrade
          spec:
            subscriptionId: $SUB_ID
            resourceGroup: $RESOURCE_GROUP
            clusterName: $CLUSTER_NAME
            nodePools:
              - name: agentpool
                properties: {
                  orchestratorVersion: $K8S_VERSION,
                }
          EOF

      - name: Execute Start
        if: ${{ inputs.task == 'execute' }}
        run: echo "::notice::Update started, monitor node pool manager logs and/or Azure Portal"

      - name: Cleanup
        if: ${{ inputs.task == 'cleanup' }}
        run: |
          kubectl -n operations delete nodepoolmanager.k8smanagers.greyridge.com/agentpool-upgrade

      - name: Cleanup Complete
        if: ${{ inputs.task == 'cleanup' }}
        run: echo "::notice::Cleanup completed successfully!"
