name: 2. Create Surge Pools

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Execute or Cleanup"
        required: true
        default: "execute"
        type: choice
        options:
          - execute
          - cleanup
      version:
        description: "Target Kubernetes version"
        required: false
      colour:
        description: "Colour of surge pools to create"
        required: true
        type: choice
        options:
          - blue
          - green

jobs:
  do_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Execute
        if: ${{ inputs.task == 'execute' }}
        run: |
          SUB_ID=${{ vars.SUB_ID }}
          RESOURCE_GROUP=${{ vars.RESOURCE_GROUP }}
          CLUSTER_NAME=${{ vars.CLUSTER_NAME }}
          K8S_VERSION=${{ inputs.version }}
          COLOUR=${{ inputs.colour }}
          
          cat <<EOF | kubectl apply -n operations -f -
          apiVersion: k8smanagers.greyridge.com/v1
          kind: NodePoolManager
          metadata:
            labels:
              app.kubernetes.io/name: nodepoolmanager
              app.kubernetes.io/managed-by: kustomize
            name: surge-pools
          spec:
            subscriptionId: $SUB_ID
            resourceGroup: $RESOURCE_GROUP
            clusterName: $CLUSTER_NAME
            nodePools:
              - name: cntrl$COLOUR
                properties: {
                  vmSize: Standard_DS2_v2,
                  minCount: 0,
                  maxCount: 1,
                  enableAutoScaling: true,
                  orchestratorVersion: $K8S_VERSION,
                }
              - name: svcs$COLOUR
                properties: {
                  vmSize: Standard_DS2_v2,
                  minCount: 0,
                  maxCount: 3,
                  enableAutoScaling: true,
                  orchestratorVersion: $K8S_VERSION,
                }
          EOF

      - name: Execute Start
        if: ${{ inputs.task == 'execute' }}
        run: echo "::notice::Creation of surge pools started, monitor node pool manager logs and/or Azure Portal"

      - name: Cleanup
        if: ${{ inputs.task == 'cleanup' }}
        run: |
          kubectl -n operations delete nodepoolmanager.k8smanagers.greyridge.com/surge-pools

      - name: Cleanup Complete
        if: ${{ inputs.task == 'cleanup' }}
        run: echo "::notice::Cleanup completed successfully!"
